import keyMirror from 'key-mirror';

export default keyMirror({
    SIGN_OUT: null,
    SEND_MESSAGE: null,
    SET_USER_MESSAGE: null,
    SIGN_IN_WITH_GOOGLE: null,
    SET_AUTH_USER_STORE: null,
    SET_IS_READY_FOR_GAME: null,
    SET_USERS_MESSAGES_STORE: null,
    SET_DATA_TO_LOCAL_STORAGE: null,
    REMOVE_DATA_FROM_LOCAL_STORAGE: null,
    REMOVE_ITEM_FROM_LOCAL_STORAGE: null,
    SET_AUTH_USER_DATABASE_ID_STORE: null,
    SET_CURRENT_USER_READINESS_STORE: null,
    CLEAR_CURRENT_USER_READINESS_STORE: null,
    SET_IS_USER_READY_TO_START_QUIZ_STORE: null,
    SET_USER_DATA_FROM_LOCAL_STORAGE_STORE: null,
});